/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Skills: typeof import('./components/Skills.vue')['default']
    Snake: typeof import('./components/Snake.vue')['default']
    Socials: typeof import('./components/Socials.vue')['default']
    Test: typeof import('./components/Test.vue')['default']
    UsePreferredDark: typeof import('@vueuse/components')['UsePreferredDark']
  }
}
